# Generated by Django 2.2.3 on 2019-07-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(db_index=True, help_text="User's first name who will own a task", max_length=20)),
                ('last_name', models.CharField(db_index=True, help_text="User's last name", max_length=20)),
            ],
            options={
                'verbose_name_plural': 'User',
                'ordering': ['first_name', 'last_name'],
                'unique_together': {('first_name', 'last_name')},
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The task name', max_length=30)),
                ('priority', models.CharField(choices=[('L', 'Low'), ('M', 'Meduim'), ('H', 'High')], default='L', help_text='the priority of a task', max_length=1)),
                ('start', models.DateTimeField(db_index=True, help_text='the start date and time of a task')),
                ('end', models.DateTimeField(help_text='the end date and time of a task')),
                ('owner', models.ForeignKey(help_text='The task owner', on_delete=django.db.models.deletion.CASCADE, to='tasks.User')),
                ('parent_task', models.ForeignKey(help_text='the parent task of this sub task', on_delete=django.db.models.deletion.CASCADE, related_name='sub_task', to='tasks.Task')),
            ],
            options={
                'verbose_name_plural': 'Task',
                'ordering': ('start',),
            },
        ),
    ]
