# Generated by Django 2.2.3 on 2019-07-24 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190724_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.ForeignKey(help_text='the parent task of this sub task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_task', to='tasks.Task'),
        ),
    ]
